@startuml
' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity "users" as users {
  *id : number <<generated>>
  --
  avatar : string
  name : string
  password : string
  phone_number : string
}

entity "social_providers" as social_providers {
  *id : number <<generated>>
  --
  name : string
}

entity "user_socials" as user_socials {
  *social_provider_id : number <<FK>>
  *user_id : number <<FK>>
  *social_id: string
  --
}

entity "tweets" as tweets {
  *id : number <<generated>>
  --
  *user_id : number <<FK>>
  *song_id : number <<FK>>
  *video_url : string
  description : string
}

entity "comments" as comments {
  *id : number <<generated>>
  --
  *tweet_id : number <<FK>>
  *user_id : number <<FK>>
  parent_id : string
  *content : string
}

entity "likes" as likes {
  *likeable_name : number 'user/tweet/comment'
  *likeable_id : number
  *user_id : number <<FK>>
  --
}

entity "songs" as songs {
  *id : number <<generated>>
  --
  *song_url : string
  *user_id : number <<FK>>
  *title: string
}

entity "tags" as tags {
  *slug : string
  --
  _tweets_count : number
  description : string
}

entity "tags_tweets" as tags_tweets {
  *tweet_id : number <<FK>>
  *tag_slug : string <<FK>>
}



@enduml