name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            frontend/node_modules
            ~/.gradle/caches
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-        
      - name: set env
        run: |
          export BRANCH_NAME=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g")
          export GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)
          echo "::set-env name=BRANCH_NAME::${BRANCH_NAME}"
          echo "::set-env name=GITHUB_SHA_SHORT::${GITHUB_SHA_SHORT}"
      - name: set up share modules
        working-directory: ./share
        run: |
          npm install
          npm run build
      - name: npm install
        working-directory: ./frontend
        run: |
          npm install       
      - name: build for android
        working-directory: ./frontend
        run: |
          npm run build
          npx cap sync
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        working-directory: ./frontend
        run: |
          pushd android && ./gradlew assembleDebug --stacktrace && popd
      - name: Upload debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-android-${{env.BRANCH_NAME}}-${{env.GITHUB_SHA_SHORT}}
          path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
